<style>
/* Dashboard-only product layer: intentional hierarchy, rhythm and responsive behavior. */
.pm-dashboard-v4{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#101828}
.pm-dashboard-v4 .pm-eyebrow{font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#667085;margin:0 0 8px}
.pm-dashboard-v4 .pm-dashboard-header{display:flex;justify-content:space-between;gap:32px;align-items:flex-end;padding:4px 0 24px;border-bottom:1px solid #eaecf0;margin-bottom:24px}
.pm-dashboard-v4 .pm-dashboard-heading h1{margin:0;font-size:30px;line-height:1.18;letter-spacing:-.025em;font-weight:700;color:#101828}
.pm-dashboard-v4 .pm-dashboard-heading>p:last-child{margin:8px 0 0;color:#667085;font-size:14px;line-height:1.6}
.pm-dashboard-v4 .pm-header-actions{display:flex;align-items:center;gap:12px;flex-shrink:0}
.pm-dashboard-v4 .pm-dashboard-action{display:inline-flex;align-items:center;gap:10px;height:40px;padding:0 14px;border:1px solid #d0d5dd;border-radius:8px;background:#fff;color:#344054;font-size:13px;font-weight:650;text-decoration:none;box-shadow:0 1px 2px rgba(16,24,40,.04);transition:.16s ease}
.pm-dashboard-v4 .pm-dashboard-action:hover{border-color:#98a2b3;background:#f9fafb}
.pm-dashboard-v4 .pm-header-date{height:40px;display:flex;align-items:center;gap:8px;padding:0 2px;color:#667085;font-size:12px;font-weight:600;white-space:nowrap}
.pm-dashboard-v4 .pm-date-dot{width:7px;height:7px;border-radius:50%;background:#12b76a}
.pm-dashboard-v4 .pm-kpi,.pm-dashboard-v4 .pm-panel,.pm-dashboard-v4 .pm-report-strip{border:1px solid #eaecf0;border-radius:10px;background:#fff;box-shadow:0 1px 2px rgba(16,24,40,.03)}
.pm-dashboard-v4 .pm-admin-kpi-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}
.pm-dashboard-v4 .pm-kpi{min-height:126px;padding:18px 18px 16px;position:relative;overflow:hidden;display:flex;flex-direction:column;align-items:flex-start;justify-content:space-between;text-decoration:none;color:inherit;transition:border-color .16s ease,box-shadow .16s ease,transform .16s ease}
.pm-dashboard-v4 .pm-kpi:hover{border-color:#d0d5dd;box-shadow:0 5px 16px rgba(16,24,40,.06);transform:translateY(-1px)}
.pm-dashboard-v4 .pm-kpi-label{font-size:12px;font-weight:650;color:#667085}
.pm-dashboard-v4 .pm-kpi strong{font-size:28px;line-height:1;font-weight:700;letter-spacing:-.025em;color:#101828}
.pm-dashboard-v4 .pm-kpi-note{font-size:11px;color:#98a2b3}
.pm-dashboard-v4 .pm-kpi-primary{border-color:#d6e4ff}
.pm-dashboard-v4 .pm-kpi-primary:before{content:"";position:absolute;left:0;top:0;bottom:0;width:3px;background:#2563eb}
.pm-dashboard-v4 .pm-kpi-trend{position:absolute;right:14px;top:15px;padding:4px 7px;border-radius:5px;background:#eff6ff;color:#175cd3;font-size:10px;font-weight:700}
.pm-dashboard-v4 .pm-analytics-grid{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(360px,.85fr);gap:16px;margin-bottom:16px}
.pm-dashboard-v4 .pm-chart-panel{min-height:348px;padding:22px}
.pm-dashboard-v4 .pm-chart-heading{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:24px}
.pm-dashboard-v4 .pm-chart-heading h2,.pm-dashboard-v4 .pm-panel-heading h2,.pm-dashboard-v4 .pm-focus-panel h2{margin:0;font-size:17px;line-height:1.3;letter-spacing:-.01em;color:#101828}
.pm-dashboard-v4 .pm-chart-heading span{display:block;margin-top:5px;color:#667085;font-size:12px}
.pm-dashboard-v4 .pm-chart-heading>a,.pm-dashboard-v4 .pm-panel-heading>a{font-size:12px;font-weight:650;color:#175cd3;text-decoration:none;white-space:nowrap}
.pm-dashboard-v4 .pm-bar-chart{height:235px;display:grid;grid-template-columns:repeat(7,1fr);gap:12px;align-items:end;border-bottom:1px solid #eaecf0;padding:0 4px}
.pm-dashboard-v4 .pm-bar-item{height:100%;display:flex;flex-direction:column;align-items:center;justify-content:flex-end;min-width:0}
.pm-dashboard-v4 .pm-bar-value{font-size:10px;font-weight:700;color:#475467;margin-bottom:6px}
.pm-dashboard-v4 .pm-bar-track{width:100%;max-width:34px;height:175px;background:#f2f4f7;border-radius:5px 5px 0 0;display:flex;align-items:flex-end;overflow:hidden}
.pm-dashboard-v4 .pm-bar-fill{width:100%;min-height:8px;background:#2563eb;border-radius:5px 5px 0 0}
.pm-dashboard-v4 .pm-bar-item strong{font-size:11px;color:#475467;margin-top:9px}.pm-dashboard-v4 .pm-bar-item small{font-size:10px;color:#98a2b3;margin-top:2px;margin-bottom:8px}
.pm-dashboard-v4 .pm-pipeline-list{display:flex;flex-direction:column;gap:20px;margin-top:10px}.pm-dashboard-v4 .pm-pipeline-label{display:flex;justify-content:space-between;gap:12px;font-size:12px;color:#475467;margin-bottom:7px}.pm-dashboard-v4 .pm-pipeline-label strong{color:#101828}.pm-dashboard-v4 .pm-pipeline-track{height:8px;background:#f2f4f7;border-radius:99px;overflow:hidden}.pm-dashboard-v4 .pm-pipeline-track span{display:block;height:100%;min-width:3px;background:#344054;border-radius:99px}.pm-dashboard-v4 .pm-pipeline-total{display:flex;align-items:baseline;gap:8px;margin-top:25px;padding-top:18px;border-top:1px solid #eaecf0}.pm-dashboard-v4 .pm-pipeline-total strong{font-size:24px}.pm-dashboard-v4 .pm-pipeline-total span{font-size:11px;color:#98a2b3}
.pm-dashboard-v4 .pm-report-strip{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:16px 18px;margin-bottom:16px}.pm-dashboard-v4 .pm-report-strip>div{display:flex;align-items:center;gap:13px;min-width:0}.pm-dashboard-v4 .pm-report-icon{width:34px;height:34px;display:grid;place-items:center;border:1px solid #d0d5dd;border-radius:7px;color:#344054;font-size:15px}.pm-dashboard-v4 .pm-report-strip strong{display:block;font-size:13px}.pm-dashboard-v4 .pm-report-strip>div span:last-child{display:block;margin-top:3px;font-size:11px;color:#667085}.pm-dashboard-v4 .pm-report-strip>a{font-size:12px;font-weight:650;color:#175cd3;white-space:nowrap;text-decoration:none}
.pm-dashboard-v4 .pm-content-grid{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(300px,.75fr);gap:16px}.pm-dashboard-v4 .pm-panel{overflow:hidden}.pm-dashboard-v4 .pm-panel-heading{display:flex;justify-content:space-between;align-items:center;padding:19px 20px;border-bottom:1px solid #eaecf0}.pm-dashboard-v4 .pm-task-list{padding:0}.pm-dashboard-v4 .pm-task-row{display:flex;align-items:center;gap:12px;min-height:66px;padding:12px 20px;border-bottom:1px solid #f2f4f7;transition:background .15s ease}.pm-dashboard-v4 .pm-task-row:last-child{border-bottom:0}.pm-dashboard-v4 .pm-task-row:hover{background:#f9fafb}.pm-dashboard-v4 .pm-task-marker{width:8px;height:8px;border-radius:50%;background:#f79009;flex:0 0 auto}.pm-dashboard-v4 .pm-task-marker.done{background:#12b76a}.pm-dashboard-v4 .pm-task-main{min-width:0;flex:1}.pm-dashboard-v4 .pm-task-main strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px;font-weight:650;color:#101828}.pm-dashboard-v4 .pm-task-main span{display:block;margin-top:3px;font-size:11px;color:#98a2b3}.pm-dashboard-v4 .pm-status-chip,.pm-dashboard-v4 .pm-priority{font-size:10px;font-weight:700;padding:5px 8px;border-radius:5px;background:#f2f4f7;color:#475467;white-space:nowrap}.pm-dashboard-v4 .pm-focus-panel{padding:22px;border-top:3px solid #101828}.pm-dashboard-v4 .pm-focus-panel>p:not(.pm-eyebrow){margin:9px 0 0;font-size:13px;line-height:1.65;color:#667085}.pm-dashboard-v4 .pm-focus-rule{height:1px;background:#eaecf0;margin:22px 0}.pm-dashboard-v4 .pm-quick-links{margin-top:20px}.pm-dashboard-v4 .pm-quick-links a{display:flex;align-items:center;justify-content:space-between;padding:13px 0;border-bottom:1px solid #eef0f3;color:#344054;font-size:12px;font-weight:650;text-decoration:none}.pm-dashboard-v4 .pm-quick-links a:last-child{border-bottom:0}
.pm-dashboard-v4 .pm-attendance-hero{display:grid;grid-template-columns:1fr auto;gap:28px;align-items:center;padding:24px;margin-bottom:16px;border:1px solid #d0d5dd;border-radius:10px;background:#fff}.pm-dashboard-v4 .pm-attendance-copy h2{margin:0;font-size:24px;letter-spacing:-.02em}.pm-dashboard-v4 .pm-attendance-copy>p{margin:7px 0 0;color:#667085;font-size:13px}.pm-dashboard-v4 .pm-attendance-meta{display:flex;gap:28px;margin-top:20px}.pm-dashboard-v4 .pm-attendance-meta span{display:flex;flex-direction:column;gap:3px}.pm-dashboard-v4 .pm-attendance-meta strong{font-size:15px}.pm-dashboard-v4 .pm-attendance-meta small,.pm-dashboard-v4 .pm-attendance-action small{font-size:10px;color:#98a2b3}.pm-dashboard-v4 .pm-attendance-action{display:flex;flex-direction:column;align-items:flex-end;gap:9px}.pm-dashboard-v4 .pm-clock-button{min-width:180px;height:46px;border:0;border-radius:8px;background:#175cd3;color:#fff;font-size:13px;font-weight:700;display:inline-flex;align-items:center;justify-content:center;gap:9px;cursor:pointer;box-shadow:0 2px 4px rgba(16,24,40,.12)}.pm-dashboard-v4 .pm-clock-button:disabled{opacity:.6;cursor:not-allowed}.pm-dashboard-v4 .pm-inline-error{padding:11px 14px;margin:-4px 0 16px;border:1px solid #fecdca;border-radius:8px;background:#fef3f2;color:#b42318;font-size:12px}.pm-dashboard-v4 .pm-kpi-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-bottom:16px}
@media(max-width:1100px){.pm-dashboard-v4 .pm-admin-kpi-grid{grid-template-columns:repeat(2,1fr)}.pm-dashboard-v4 .pm-analytics-grid,.pm-dashboard-v4 .pm-content-grid{grid-template-columns:1fr}.pm-dashboard-v4 .pm-chart-panel{min-height:0}}
@media(max-width:700px){.pm-dashboard-v4 .pm-dashboard-header{display:block;padding-bottom:18px;margin-bottom:18px}.pm-dashboard-v4 .pm-header-actions{margin-top:16px;justify-content:space-between}.pm-dashboard-v4 .pm-dashboard-heading h1{font-size:25px}.pm-dashboard-v4 .pm-admin-kpi-grid,.pm-dashboard-v4 .pm-kpi-grid{grid-template-columns:1fr}.pm-dashboard-v4 .pm-kpi{min-height:104px}.pm-dashboard-v4 .pm-chart-panel{padding:17px}.pm-dashboard-v4 .pm-bar-chart{gap:5px}.pm-dashboard-v4 .pm-bar-track{max-width:26px}.pm-dashboard-v4 .pm-report-strip{display:block}.pm-dashboard-v4 .pm-report-strip>a{display:inline-block;margin:13px 0 0 47px}.pm-dashboard-v4 .pm-attendance-hero{grid-template-columns:1fr;padding:18px}.pm-dashboard-v4 .pm-attendance-action{align-items:stretch}.pm-dashboard-v4 .pm-clock-button{width:100%}.pm-dashboard-v4 .pm-attendance-meta{gap:18px}.pm-dashboard-v4 .pm-task-row{padding:12px 16px}.pm-dashboard-v4 .pm-panel-heading{padding:16px}.pm-dashboard-v4 .pm-focus-panel{padding:18px}}
</style>
