<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');
:root{--ui-font:'Poppins',system-ui,sans-serif;--ui-text:#111827;--ui-muted:#6b7280;--ui-border:#d7dde7;--ui-surface:#fff;--ui-soft:#f7f9fc;--ui-brand:#2563eb;--ui-ring:rgba(37,99,235,.18);--ui-radius:12px}
html,body,.fi-body,.fi-layout,.fi-main,.fi-page,.fi-modal-window,.fi-dropdown-panel,.fi-ta-content{font-family:var(--ui-font)!important;color:var(--ui-text)!important}
.fi-main,.fi-page,.fi-page-content,.fi-section,.fi-modal-content{min-width:0!important;max-width:100%!important}.fi-page{width:100%!important}.fi-page-content>*{min-width:0!important}
.fi-page-header,.fi-header,.fi-ta-header-toolbar,.fi-ac-action-list{min-width:0!important;flex-wrap:wrap!important}.fi-page-header-actions,.fi-header-actions{min-width:0!important;flex-wrap:wrap!important}
.fi-input-wrp,.fi-select-input,.fi-fo-select .fi-input-wrp,.fi-fo-text-input .fi-input-wrp,.fi-fo-textarea .fi-input-wrp{background:var(--ui-surface)!important;border:1px solid var(--ui-border)!important;border-radius:var(--ui-radius)!important;box-shadow:0 1px 2px rgba(15,23,42,.04)!important;color:var(--ui-text)!important}
.fi-input-wrp:focus-within,.fi-fo-field-wrp:focus-within .fi-input-wrp{border-color:var(--ui-brand)!important;box-shadow:0 0 0 4px var(--ui-ring)!important}
input,textarea,select,[contenteditable=true],.fi-input,.fi-select-input,.fi-fo-field-wrp input,.fi-fo-field-wrp textarea{font-family:var(--ui-font)!important;color:var(--ui-text)!important;background:transparent!important;-webkit-text-fill-color:var(--ui-text)!important;caret-color:var(--ui-brand)!important;font-size:13px!important;font-weight:500!important;opacity:1!important}input::placeholder,textarea::placeholder{color:#8b95a7!important;opacity:1!important}
.fi-fo-field-wrp-label,.fi-fo-field-wrp-label span,.fi-fo-field-wrp-label label{color:var(--ui-text)!important;font-weight:600!important;font-size:12px!important}
.fi-fo-textarea textarea{min-height:160px!important;line-height:1.7!important;padding:14px!important;resize:vertical!important}
.fi-fo-rich-editor,.fi-rich-editor{background:#fff!important;border:1px solid var(--ui-border)!important;border-radius:var(--ui-radius)!important;overflow:hidden!important}.fi-fo-rich-editor [contenteditable=true],.fi-rich-editor [contenteditable=true]{background:#fff!important;color:var(--ui-text)!important;-webkit-text-fill-color:var(--ui-text)!important;min-height:160px!important;padding:14px!important;line-height:1.7!important}
.fi-fo-rich-editor button,.fi-rich-editor button{color:#1f2937!important;background:#fff!important;border:1px solid var(--ui-border)!important;border-radius:8px!important;min-width:34px!important;min-height:34px!important;font-weight:700!important;opacity:1!important}.fi-fo-rich-editor button:hover,.fi-rich-editor button:hover{background:#f3f6fb!important;border-color:#9ca7b8!important}.fi-fo-rich-editor button[aria-pressed=true],.fi-rich-editor button[aria-pressed=true]{background:var(--ui-brand)!important;border-color:var(--ui-brand)!important;color:#fff!important}
.fi-dropdown-panel,.fi-select-options,.choices__list--dropdown,[role=listbox],[data-floating-ui-portal] .fi-dropdown-panel{background:#fff!important;color:var(--ui-text)!important;border:1px solid var(--ui-border)!important;border-radius:12px!important;box-shadow:0 18px 48px rgba(15,23,42,.14)!important}.fi-dropdown-panel *,[role=listbox] *,[data-floating-ui-portal] .fi-dropdown-panel *{color:var(--ui-text)!important}.fi-dropdown-list-item,.fi-select-option,[role=option]{background:#fff!important;color:var(--ui-text)!important;font-family:var(--ui-font)!important}.fi-dropdown-list-item:hover,.fi-select-option:hover,[role=option]:hover{background:#eef4ff!important;color:#111827!important}
.fi-dropdown-panel input,[role=listbox] input,[data-floating-ui-portal] input{background:#fff!important;color:#111827!important;-webkit-text-fill-color:#111827!important;border-color:var(--ui-border)!important}
.fi-fo-field-wrp .fi-badge,.fi-select-input .fi-badge{background:#eef4ff!important;color:#173b77!important;border:1px solid #cfe0ff!important;font-weight:600!important}.fi-badge button,.fi-select-input button{color:#334155!important}
.fi-date-time-picker-panel,.fi-date-picker-panel,.flatpickr-calendar,.flatpickr-calendar *,[data-floating-ui-portal] .flatpickr-calendar,[data-floating-ui-portal] .flatpickr-calendar *{background:#fff!important;color:#111827!important;-webkit-text-fill-color:#111827!important;font-family:var(--ui-font)!important}.flatpickr-day{color:#111827!important;border-radius:8px!important}.flatpickr-day:hover{background:#eef4ff!important}.flatpickr-day.selected,.flatpickr-day.selected:hover{background:var(--ui-brand)!important;color:#fff!important;-webkit-text-fill-color:#fff!important}.flatpickr-months .flatpickr-month,.flatpickr-current-month,.flatpickr-current-month input,.flatpickr-weekday{color:#111827!important}.flatpickr-prev-month svg,.flatpickr-next-month svg{fill:#111827!important}
.fi-ta-content{overflow-x:auto!important}.fi-ta-table{min-width:700px!important}.fi-ta-ctn{max-width:100%!important;overflow:hidden!important}
.fi-modal-window{width:min(860px,calc(100vw - 32px))!important;max-width:860px!important;background:#fff!important;border-radius:18px!important;border:1px solid var(--ui-border)!important}.fi-modal-header,.fi-modal-content{background:#fff!important;color:var(--ui-text)!important}.fi-modal-footer{background:var(--ui-soft)!important}
.fi-btn{font-family:var(--ui-font)!important;border-radius:10px!important;font-weight:600!important}
@media(max-width:1024px){.fi-main{min-width:0!important;width:100%!important}.fi-page{padding-left:0!important;padding-right:0!important}.fi-ta-header-toolbar{align-items:stretch!important}.fi-page-header-actions,.fi-header-actions{width:100%!important}.fi-page-header-actions>*{flex:0 0 auto!important}}
@media(max-width:760px){.fi-page,.fi-page-content{max-width:100vw!important}.fi-ta-table{min-width:620px!important}.fi-modal-window{width:calc(100vw - 20px)!important}.fi-fo-grid{grid-template-columns:1fr!important}.fi-page-header-actions,.fi-header-actions{gap:8px!important}.fi-page-header-actions .fi-btn{flex:1 1 auto!important}}
</style>