<style>
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap');
:root{--pm-form-ink:#172033;--pm-form-muted:#667085;--pm-form-border:#d9dee8;--pm-form-focus:#2563eb;--pm-form-surface:#fff;--pm-form-soft:#f8fafc;--pm-form-disabled:#f1f4f8}
html,body,.fi-body,.fi-layout,.fi-main,.fi-page,.fi-page-content,.fi-modal-window,.fi-modal-window *{font-family:'Poppins',ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif!important}
.fi-fo-field-wrp{min-width:0!important}.fi-fo-field-wrp-label,.fi-fo-field-wrp-label span{color:#172033!important;font-size:11px!important;font-weight:600!important;letter-spacing:.01em!important}.fi-fo-field-wrp-helper-text{color:#667085!important;font-size:10px!important}.fi-fo-field-wrp-error-message{font-size:10px!important;font-weight:500!important}
.fi-fo-field-wrp .fi-input-wrp,.fi-fo-field-wrp .fi-select,.fi-fo-field-wrp .fi-date-time-picker,.fi-fo-field-wrp .fi-date-picker{min-height:44px!important;background:#fff!important;border:1px solid #d5dae3!important;border-radius:10px!important;box-shadow:0 1px 2px rgba(16,24,40,.04)!important;transition:.16s ease!important}.fi-fo-field-wrp .fi-input-wrp:hover,.fi-fo-field-wrp .fi-select:hover{border-color:#aeb7c5!important}.fi-fo-field-wrp .fi-input-wrp:focus-within,.fi-fo-field-wrp .fi-select:focus-within{border-color:#2563eb!important;box-shadow:0 0 0 3px rgba(37,99,235,.10)!important}
.fi-fo-field-wrp input,.fi-fo-field-wrp select,.fi-fo-field-wrp textarea,.fi-input-wrp input,.fi-input-wrp select,.fi-input-wrp textarea,.fi-input,.fi-select,.fi-textarea,.fi-fo-text-input,.fi-fo-select,.fi-fo-textarea{color:#172033!important;background:transparent!important;opacity:1!important;-webkit-text-fill-color:#172033!important;caret-color:#2563eb!important;font-family:'Poppins',sans-serif!important;font-size:12px!important;font-weight:500!important;line-height:1.5!important}.fi-fo-field-wrp input::placeholder,.fi-fo-field-wrp textarea::placeholder,.fi-input-wrp input::placeholder,.fi-input-wrp textarea::placeholder{color:#98a2b3!important;opacity:1!important;-webkit-text-fill-color:#98a2b3!important}
.fi-fo-field-wrp select{min-height:42px!important;padding:0 38px 0 13px!important;cursor:pointer!important}.fi-fo-field-wrp .fi-select{min-height:44px!important;cursor:pointer!important}.fi-fo-field-wrp .fi-select [role="option"],.fi-dropdown-list-item{font-size:12px!important;font-weight:500!important;line-height:1.35!important}.fi-dropdown-list-item{min-height:40px!important;padding:9px 12px!important;border-radius:7px!important}.fi-dropdown-panel{border:1px solid #dfe4ec!important;border-radius:11px!important;background:#fff!important;color:#172033!important;box-shadow:0 18px 48px rgba(15,23,42,.14)!important}
.fi-ta-header-toolbar{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:10px!important;flex-wrap:wrap!important;min-width:0!important}.fi-ta-search-field{flex:1 1 260px!important;min-width:220px!important;max-width:560px!important}.fi-ta-search-field .fi-input-wrp{min-height:42px!important;background:#fff!important;border:1px solid #d9dee8!important;border-radius:9px!important}.fi-ta-search-field input{font-family:'Poppins',sans-serif!important;color:#172033!important;font-size:12px!important}.fi-ta-filters-trigger,.fi-ta-header-toolbar .fi-btn{min-height:42px!important;border-radius:9px!important;font-family:'Poppins',sans-serif!important;font-size:11px!important;font-weight:600!important}.fi-ta-filters-trigger{border:1px solid #d9dee8!important;background:#fff!important;color:#172033!important}.fi-ta-filters-form .fi-fo-field-wrp .fi-input-wrp,.fi-ta-filters-form .fi-fo-field-wrp .fi-select{min-height:42px!important}
.fi-fo-field-wrp .fi-input-wrp:has(input[type="search"]){min-height:44px!important}.fi-fo-field-wrp .fi-badge{font-size:10px!important;font-weight:600!important;border-radius:7px!important}
.fi-fo-field-wrp textarea,.fi-input-wrp textarea,textarea.fi-textarea,.fi-fo-textarea textarea{min-height:156px!important;height:156px!important;padding:13px 14px!important;resize:vertical!important;line-height:1.7!important;vertical-align:top!important;overflow-y:auto!important}

/* RICH TEXT — clean, bright toolbar with unmistakable formatting controls. */
.fi-fo-rich-editor,.fi-rich-editor{border:1px solid #d5dae3!important;border-radius:10px!important;background:#fff!important;overflow:hidden!important;box-shadow:0 1px 2px rgba(16,24,40,.04)!important}.fi-fo-rich-editor:focus-within,.fi-rich-editor:focus-within{border-color:#2563eb!important;box-shadow:0 0 0 3px rgba(37,99,235,.10)!important}.fi-fo-rich-editor .tiptap,.fi-fo-rich-editor [contenteditable="true"],.fi-rich-editor [contenteditable="true"]{color:#172033!important;background:#fff!important;font-family:'Poppins',sans-serif!important;font-size:12px!important;line-height:1.7!important;caret-color:#2563eb!important;-webkit-text-fill-color:#172033!important}.fi-fo-rich-editor [contenteditable="true"],.fi-rich-editor [contenteditable="true"]{min-height:156px!important;padding:13px 14px!important;outline:none!important}
.fi-fo-rich-editor button,.fi-rich-editor button,.fi-fo-rich-editor [role="button"],.fi-rich-editor [role="button"]{color:#344054!important;background:#fff!important;border:1px solid #c9d0db!important;border-radius:7px!important;min-width:32px!important;min-height:32px!important;padding:5px 8px!important;font-size:12px!important;font-weight:700!important;line-height:1!important;opacity:1!important;box-shadow:0 1px 2px rgba(16,24,40,.06)!important;visibility:visible!important}.fi-fo-rich-editor button:hover,.fi-rich-editor button:hover,.fi-fo-rich-editor [role="button"]:hover,.fi-rich-editor [role="button"]:hover{color:#101828!important;background:#f3f5f8!important;border-color:#98a2b3!important}.fi-fo-rich-editor button[aria-pressed="true"],.fi-rich-editor button[aria-pressed="true"],.fi-fo-rich-editor [aria-pressed="true"],.fi-rich-editor [aria-pressed="true"]{color:#fff!important;background:#2563eb!important;border-color:#2563eb!important}.fi-fo-rich-editor button svg,.fi-rich-editor button svg,.fi-fo-rich-editor [role="button"] svg,.fi-rich-editor [role="button"] svg{color:currentColor!important;stroke:currentColor!important;fill:none!important;width:16px!important;height:16px!important;opacity:1!important}.fi-fo-rich-editor button svg *,.fi-rich-editor button svg *{stroke:currentColor!important;fill:currentColor!important;opacity:1!important}

/* DATE / TIME PICKERS — bright product-style calendar, never dark. */
.fi-fo-field-wrp [data-datepicker],.fi-fo-field-wrp [role="dialog"],.fi-fo-field-wrp [data-popper-placement]{font-family:'Poppins',sans-serif!important;color:#172033!important}.fi-fo-field-wrp [data-datepicker],.fi-fo-field-wrp [role="dialog"]{background:#fff!important;border:1px solid #dfe4ec!important;border-radius:12px!important;box-shadow:0 18px 48px rgba(15,23,42,.14)!important}.fi-fo-field-wrp [data-datepicker] button,.fi-fo-field-wrp [role="dialog"] button{font-family:'Poppins',sans-serif!important;color:#344054!important;background:#fff!important;border-radius:7px!important}.fi-fo-field-wrp [data-datepicker] button:hover,.fi-fo-field-wrp [role="dialog"] button:hover{background:#f2f4f7!important;color:#101828!important}.fi-fo-field-wrp [data-datepicker] [aria-selected="true"],.fi-fo-field-wrp [role="dialog"] [aria-selected="true"]{background:#2563eb!important;color:#fff!important}.fi-fo-field-wrp [data-datepicker] [aria-current="date"]{color:#2563eb!important;font-weight:700!important}.fi-fo-field-wrp [data-datepicker] input,.fi-fo-field-wrp [role="dialog"] input{color:#172033!important;background:#fff!important;-webkit-text-fill-color:#172033!important}.fi-fo-field-wrp [data-datepicker] svg,.fi-fo-field-wrp [role="dialog"] svg{color:#475467!important;opacity:1!important}

/* SELECT / RELATIONSHIP PRESENTATION — light, clean chips and menus. */
.fi-fo-field-wrp .fi-select,.fi-fo-field-wrp .fi-input-wrp{color:#172033!important}.fi-fo-field-wrp [data-selected="true"],.fi-fo-field-wrp .fi-badge{background:#eef4ff!important;color:#1d4ed8!important;border:1px solid #cfe0ff!important}.fi-fo-field-wrp [data-selected="true"] svg,.fi-fo-field-wrp .fi-badge svg{color:currentColor!important}.fi-fo-field-wrp .fi-select [role="option"][aria-selected="true"],.fi-dropdown-list-item[aria-selected="true"]{background:#f0f5ff!important;color:#1d4ed8!important}
.fi-fo-field-wrp input:disabled,.fi-fo-field-wrp select:disabled,.fi-fo-field-wrp textarea:disabled{background:#f1f4f8!important;color:#98a2b3!important}
.fi-fo-field-wrp input[type="checkbox"],.fi-fo-field-wrp input[type="radio"]{accent-color:#2563eb!important}.fi-fo-field-wrp .fi-checkbox-list,.fi-fo-field-wrp .fi-radio-list{gap:8px!important}.fi-fo-field-wrp .fi-checkbox-label,.fi-fo-field-wrp .fi-radio-label{font-size:12px!important;font-weight:500!important;color:#172033!important}.fi-fo-field-wrp [role="switch"]{border-radius:999px!important}
.fi-fo-field-wrp .fi-fo-file-upload,.fi-fo-field-wrp [data-slot="file-upload"]{border:1px dashed #cbd3df!important;border-radius:10px!important;background:#f8fafc!important;font-family:'Poppins',sans-serif!important}.fi-fo-field-wrp .fi-fo-file-upload:hover,.fi-fo-field-wrp [data-slot="file-upload"]:hover{border-color:#2563eb!important;background:#f5f9ff!important}
.fi-fo-component-ctn,.fi-fo-grid{min-width:0!important}.fi-modal-window{width:min(780px,calc(100vw - 32px))!important;max-width:780px!important;background:#fff!important;border:1px solid #e3e7ee!important;border-radius:14px!important;box-shadow:0 24px 70px rgba(15,23,42,.16)!important;overflow:hidden!important}.fi-modal-header{padding:20px 24px!important;background:#fff!important;border-bottom:1px solid #edf0f4!important}.fi-modal-content{padding:22px 24px!important;background:#fff!important}.fi-modal-footer{padding:15px 24px!important;background:#fafbfc!important;border-top:1px solid #edf0f4!important}.fi-modal-header-heading{color:#172033!important;font-size:18px!important;font-weight:700!important}.fi-modal-footer .fi-btn,.fi-modal-content .fi-btn{min-height:40px!important;border-radius:8px!important;font-size:11px!important;font-weight:600!important}
:where(button,a,input,select,textarea,[contenteditable="true"]):focus-visible{outline:2px solid rgba(37,99,235,.45)!important;outline-offset:2px!important}
@media(max-width:760px){.fi-ta-header-toolbar{align-items:stretch!important;gap:8px!important}.fi-ta-search-field{flex:1 1 100%!important;max-width:none!important;min-width:0!important}.fi-ta-header-toolbar .fi-btn,.fi-ta-filters-trigger{flex:0 0 auto!important}.fi-modal-window{width:calc(100vw - 20px)!important;max-width:none!important;border-radius:12px!important}.fi-modal-header{padding:17px 16px!important}.fi-modal-content{padding:17px 16px!important}.fi-modal-footer{padding:13px 16px!important}.fi-fo-field-wrp .fi-input-wrp,.fi-fo-field-wrp .fi-select{min-height:42px!important}.fi-fo-field-wrp textarea,.fi-input-wrp textarea,textarea.fi-textarea,.fi-fo-textarea textarea,.fi-fo-rich-editor [contenteditable="true"],.fi-rich-editor [contenteditable="true"]{min-height:135px!important;height:135px!important}.fi-fo-rich-editor button,.fi-rich-editor button,.fi-fo-rich-editor [role="button"],.fi-rich-editor [role="button"]{min-width:30px!important;min-height:30px!important;padding:4px 7px!important}}
</style>
