<style>
:root{--pm-shell-sidebar:264px;--pm-shell-top:68px;--pm-shell-ink:#172033;--pm-shell-muted:#7a8497;--pm-shell-line:#e8ebf0;--pm-shell-blue:#315efb;--pm-shell-bg:#f6f7f9}
[x-cloak]{display:none!important}
.pm-product-shell{font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.pm-shell-sidebar{position:fixed;z-index:100;inset:0 auto 0 0;width:var(--pm-shell-sidebar);display:flex;flex-direction:column;background:#fff;border-right:1px solid var(--pm-shell-line);color:var(--pm-shell-ink)}
.pm-shell-brand{height:var(--pm-shell-top);display:flex;align-items:center;padding:0 20px;border-bottom:1px solid var(--pm-shell-line)}
.pm-brand-link{display:flex;align-items:center;gap:11px;min-width:0;color:inherit;text-decoration:none}.pm-brand-mark{display:grid;place-items:center;flex:none;width:34px;height:34px;border-radius:9px;background:#172033;color:#fff;font-size:14px;font-weight:800}.pm-brand-logo{width:34px;height:34px;border-radius:9px;object-fit:cover}.pm-brand-copy{min-width:0;display:flex;flex-direction:column;line-height:1.2}.pm-brand-copy strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:13px;font-weight:760;letter-spacing:-.01em}.pm-brand-copy small{margin-top:4px;color:var(--pm-shell-muted);font-size:10px;font-weight:550}.pm-sidebar-close{display:none;margin-left:auto;border:0;background:none;font-size:24px;color:#7a8497}
.pm-shell-nav{flex:1;overflow-y:auto;padding:17px 12px}.pm-nav-label{margin:18px 10px 7px;color:#9aa2b1;font-size:9px;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.pm-nav-label:first-child{margin-top:4px}.pm-nav-item{position:relative;display:flex;align-items:center;gap:11px;height:40px;margin:2px 0;padding:0 11px;border-radius:8px;color:#697386;text-decoration:none;font-size:12px;font-weight:620;transition:background .15s ease,color .15s ease}.pm-nav-item:hover{background:#f3f5f8;color:#172033}.pm-nav-item.is-active{background:#eef3ff;color:#2854dc;font-weight:720}.pm-nav-item.is-active:before{content:"";position:absolute;left:-12px;width:3px;height:20px;border-radius:0 3px 3px 0;background:var(--pm-shell-blue)}.pm-nav-icon{display:grid;place-items:center;width:20px;color:#8b94a4;font-size:16px;line-height:1}.pm-nav-item.is-active .pm-nav-icon{color:var(--pm-shell-blue)}
.pm-shell-account{position:relative;padding:12px;border-top:1px solid var(--pm-shell-line)}.pm-account-card{display:flex;align-items:center;gap:9px;padding:9px;border-radius:9px}.pm-account-card:hover{background:#f7f8fa}.pm-account-copy{min-width:0;flex:1;display:flex;flex-direction:column}.pm-account-copy strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#344054;font-size:11px;font-weight:700}.pm-account-copy small{margin-top:3px;color:#98a2b3;font-size:9px}.pm-account-menu{border:0;background:none;color:#98a2b3;font-size:12px;letter-spacing:2px;cursor:pointer}.pm-user-avatar{display:grid;place-items:center;flex:none;width:30px;height:30px;border-radius:50%;background:#e9eefc;color:#3153ae;font-size:10px;font-weight:800}.pm-user-avatar-small{width:32px;height:32px}.pm-account-popover{position:absolute;right:12px;bottom:58px;width:160px;padding:5px;background:#fff;border:1px solid var(--pm-shell-line);border-radius:9px;box-shadow:0 12px 28px rgba(23,32,51,.12)}.pm-account-popover form,.pm-account-popover button{width:100%}.pm-account-popover button{padding:9px 10px;border:0;border-radius:6px;background:#fff;color:#344054;text-align:left;font-size:11px;font-weight:650;cursor:pointer}.pm-account-popover button:hover{background:#f4f6f8}
.pm-shell-topbar{position:fixed;z-index:90;top:0;right:0;left:var(--pm-shell-sidebar);height:var(--pm-shell-top);display:flex;align-items:center;justify-content:space-between;padding:0 30px;background:rgba(255,255,255,.97);border-bottom:1px solid var(--pm-shell-line)}.pm-shell-search{display:flex;align-items:center;gap:9px;width:300px;height:36px;padding:0 10px;border:1px solid #e2e6ec;border-radius:7px;background:#fafbfc;color:#9aa2b1}.pm-shell-search span{font-size:19px}.pm-shell-search input{min-width:0;flex:1;border:0;outline:0;background:transparent;color:#344054;font-size:11px}.pm-shell-search input::placeholder{color:#a2a9b5}.pm-shell-search kbd{padding:2px 5px;border:1px solid #e1e5eb;border-radius:4px;background:#fff;color:#98a2b3;font:500 9px ui-monospace,SFMono-Regular,monospace}.pm-topbar-actions{display:flex;align-items:center;gap:13px}.pm-topbar-icon{position:relative;border:0;background:none;color:#667085;font-size:20px;cursor:pointer}.pm-topbar-icon i{position:absolute;top:1px;right:0;width:5px;height:5px;border-radius:50%;background:#315efb}.pm-topbar-divider{width:1px;height:22px;background:#e7eaf0}.pm-topbar-name{color:#475467;font-size:11px;font-weight:650}.pm-mobile-menu{display:none;border:0;background:none;color:#344054;font-size:20px}
/* Give the application content a true product canvas instead of the default Filament shell. */
.fi-sidebar,.fi-topbar{display:none!important}.fi-main{margin-left:var(--pm-shell-sidebar)!important;padding-top:var(--pm-shell-top)!important;background:var(--pm-shell-bg)!important}.fi-main-ctn{padding-left:30px!important;padding-right:30px!important;background:var(--pm-shell-bg)!important}.fi-header{max-width:1440px;margin:0 auto;padding-top:26px!important}.fi-page{max-width:1440px;margin:0 auto}.fi-breadcrumbs{margin-bottom:5px!important}
.fi-layout{background:var(--pm-shell-bg)!important}.fi-body{background:var(--pm-shell-bg)!important}.fi-simple-layout{background:var(--pm-shell-bg)!important}.fi-simple-main{box-shadow:0 18px 50px rgba(23,32,51,.07)!important}
/* Make native Filament resources feel like the same product. */
.fi-section,.fi-ta-ctn,.fi-wi-widget,.fi-fo-component-ctn{border-color:#e7eaf0!important;border-radius:10px!important}.fi-section-header{padding:17px 20px!important}.fi-ta-header{background:#fafbfc!important}.fi-ta-header-cell{padding-top:12px!important;padding-bottom:12px!important}.fi-ta-row{min-height:58px!important}.fi-btn{border-radius:7px!important}.fi-input,.fi-select,.fi-textarea{border-radius:7px!important}
@media(max-width:1024px){:root{--pm-shell-sidebar:232px}.pm-shell-topbar{padding:0 22px}.fi-main-ctn{padding-left:22px!important;padding-right:22px!important}}
@media(max-width:760px){:root{--pm-shell-top:62px}.pm-shell-sidebar{transform:translateX(-100%);transition:transform .2s ease;box-shadow:none}.pm-shell-sidebar.is-open{transform:translateX(0);box-shadow:12px 0 40px rgba(23,32,51,.16)}.pm-sidebar-close{display:block}.pm-shell-backdrop{position:fixed;z-index:95;inset:0;background:rgba(23,32,51,.25)}.pm-shell-topbar{left:0;height:var(--pm-shell-top);padding:0 16px}.pm-mobile-menu{display:block}.pm-shell-search{display:none}.pm-topbar-name{display:none}.fi-main{margin-left:0!important;padding-top:var(--pm-shell-top)!important}.fi-main-ctn{padding-left:16px!important;padding-right:16px!important}.fi-header{padding-top:20px!important}.pm-nav-item.is-active:before{display:none}}
@media(max-width:480px){.pm-shell-sidebar{width:285px}.pm-topbar-actions{gap:9px}.fi-main-ctn{padding-left:12px!important;padding-right:12px!important}}
</style>
